version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5252:5252"
    environment:
      - PORT=5252
      - DB_USER=dbuser
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - CORS_ORIGIN=http://localhost:3000
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=localhost:5252
    depends_on:
      - backend
    networks:
      - app-network

  db:
    build: ./db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge