name: deploy

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install & Build
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      ############
      # Frontend #
      ############
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: web/node-app/frontend
            IMAGE_TAG: ${{ github.sha }}
            BACKEND_URL: http://web-dev-backendlb-1154123055.us-east-1.elb.amazonaws.com
        run: |
            cd frontend && docker build \
              --build-arg BACKEND_URL=${BACKEND_URL} \
              -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
            task-definition: infra/task-definitions/service.latest.json
            container-name: frontend 
            image: ${{ steps.build-image.outputs.image }}

      - name: Update App Spec File
        run: |
          sed -ie "s/<CONTAINER_NAME>/$CONTAINER_NAME/" ./appspec.json
          sed -ie "s/<CONTAINER_PORT>/$CONTAINER_PORT/" ./appspec.json
        env:
          CONTAINER_NAME: frontend 
          CONTAINER_PORT: 3000

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: web-service-node-app-prod
          cluster: web-cluster-node-app-prod
          wait-for-service-stability: true
          codedeploy-appspec: appspec.json
          codedeploy-application: deployment-app-node-app-prod
          codedeploy-deployment-group: deployment-group-node-app-prod

      ###########
      # Backend #
      ###########
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.7.0
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - name: Retrieve DB_HOST from Terraform outputs
        id: terraform-output
        run: |
          echo "Retrieving DB_HOST..."
          DB_HOST=$(terraform output -raw db_host)
          echo "DB_HOST=$DB_HOST" >> $GITHUB_ENV
        env:
          TF_WORKSPACE: fullstack-terraform-template

      - name: Build, tag, and push backend image to Amazon ECR
        id: build-backend-image
        env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: web/node-app/backend
            IMAGE_TAG: ${{ github.sha }}
            PORT: 5252
            DB_USER: postgres
            DB_HOST: ${{ env.DB_HOST }} 
            DB_NAME: postgres
            DB_PASSWORD: postgres
            DB_PORT: 5432
            CORS_ORIGIN: http://web-dev-frontendlb-894222867.us-east-1.elb.amazonaws.com
        run: |
            cd backend && docker build \
              --build-arg PORT=${PORT} \
              --build-arg DB_USER=${DB_USER} \
              --build-arg DB_HOST=${DB_HOST} \
              --build-arg DB_NAME=${DB_NAME} \
              --build-arg DB_PASSWORD=${DB_PASSWORD} \
              --build-arg DB_PORT=${DB_PORT} \
              --build-arg CORS_ORIGIN=${CORS_ORIGIN} \
              -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
            echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

      - name: Fill in the new backend image ID in the Amazon ECS task definition
        id: task-def-backend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
            task-definition: infra/task-definitions/backend-service.latest.json
            container-name: backend
            image: ${{ steps.build-backend-image.outputs.image }}

      # Add steps to update the appspec.json for the backend service
      - name: Update App Spec File for Backend
        run: |
          sed -ie "s/<BACKEND_CONTAINER_NAME>/backend/" ./appspec.json
          sed -ie "s/<BACKEND_CONTAINER_PORT>/5252/" ./appspec.json
        env:
          BACKEND_CONTAINER_NAME: backend
          BACKEND_CONTAINER_PORT: 5252

      # Add steps to deploy the backend ECS task definition
      - name: Deploy Backend Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def-backend.outputs.task-definition }}
          service: backend-service-${{ env.PROJECT_ID }}-${{ env.ENVIRONMENT }}
          cluster: backend-cluster-${{ env.PROJECT_ID }}-${{ env.ENVIRONMENT }}
          wait-for-service-stability: true
        env:
          PROJECT_ID: node-app
          ENVIRONMENT: prod

